- name: Send request to API (CTS trace)
  uri:
    url: "{{ AUTH_URL_CTS }}/{{ PROJECT_ID }}/{{ cts_tracker_name }}/trace?limit={{ cts_limit }}&to={{ lookup('pipe','date +%s --date=\"' + cts_to + '\"') }}000&from={{ lookup('pipe','date +%s --date=\"' + cts_from + '\"') }}000&trace_name={{ cts_trace_name }}"
    method: GET
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: ctslist
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: ctslist.status == 200
  changed_when: false

- debug:
    msg: "{{ (ctslist.content|from_json)|json_query('traces[].[' + cts_trace_param +']') }}"
